**Numpy**
- extension package to python for multi dimensional arrays
- numpy is array oriented computing 
- it is designed for scientific computation
- closer to hardware (effeiciency)
- sometimes we also denoted as "ndarray"
- Homogeneous

**Advantages of arrays**
- less memory
- fast
- convenient

In [19]:
# one dimentional array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(type(a))

a.dtype

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


dtype('int32')

In [23]:
print(a[0])
print(a[:7:])
print(a[[1,5]])

1
[1 2 3 4 5 6 7]
[2 6]


In [29]:
print(np.arange(10))
print(np.arange(5,20))
print(np.arange(5,20,4))
print(np.arange(20,5,-1))

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  9 13 17]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6]


In [32]:
b=range(1,100)
%timeit [i**5 for i in b]

64.5 µs ± 20.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
b_numpy=np.arange(1000)
%timeit b_numpy ** 5

6.52 µs ± 2.22 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
b=range(1,1000)
c=[i**2 for i in range(1000)]
%timeit list(map(lambda x,y:x*y,b,c))

232 µs ± 76.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [49]:
b_numpy=np.array(b)
c_numpy=np.array(c)

%timeit b_numpy * c_numpy

ValueError: operands could not be broadcast together with shapes (999,) (1000,) 

In [53]:
# two dimentional array
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [54]:
print(dir(np),end="")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [55]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
print("0 row ",b[0])
print("1st row ",b[1])
print(b[1,0])

0 row  [1 2 3 4]
1st row  [5 6 7 8]
5


In [65]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
[2]
[6]
[10]

In [67]:
b[0:,1]

array([ 2,  6, 10])

In [71]:
[6,7]
[10,11]

array([ 9, 10, 11, 12])

In [72]:
b[1:,1:3]

array([[ 6,  7],
       [10, 11]])

**zero matrix/null matrix**
**ones matrix**
**identity matrix**
**Diagonal matrix**
**Transpose matrix**
**inverse matrix**

In [76]:
# zero matrix
np.zeros([3,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
# ones matrix
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
# indentity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [83]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [89]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [90]:
d.T

array([[1, 3],
       [2, 4]])

```
   1   [[d  -b]
-------[-c  a]]
ad-bc
```

In [91]:
d

array([[1, 2],
       [3, 4]])

In [92]:
np.linalg.inv(d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [188]:
np.random.random([3,3])

array([[0.50385294, 0.03728801, 0.3172598 ],
       [0.23507117, 0.81132788, 0.44668053],
       [0.21044151, 0.82683837, 0.34083706]])

In [194]:
# random value in between of range
30*np.random.random([2,3])+2

array([[19.88864463, 15.69831094, 31.05950191],
       [12.78846078,  5.77339617, 22.16773066]])

In [210]:
np.random.randint(1,30)

1

In [212]:
np.random.randint(1,30,[3,2])

array([[28,  4],
       [20,  6],
       [27, 11]])

In [219]:
np.random.randn()

-0.07502738248230505

In [223]:
np.random.randn(4,3)

array([[ 0.03512368, -1.15065738, -1.39273385],
       [ 0.59274893, -0.33170433, -1.95577824],
       [-1.33832837,  1.77599038,  0.68371143],
       [-0.69277526,  0.32821047,  0.74420687]])

In [231]:
np.random.choice(["a",1,"b","c","d","e"],[2,3])

array([['c', 'd', 'a'],
       ['c', '1', '1']], dtype='<U1')