In [5]:
import numpy as np
np.linspace(3,60,10)

array([ 3.        ,  9.33333333, 15.66666667, 22.        , 28.33333333,
       34.66666667, 41.        , 47.33333333, 53.66666667, 60.        ])

In [9]:
# multi dimentional array
#reshape
a=np.arange(18).reshape(2,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [10]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
np.arange(12).reshape(2,-3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [16]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,7],[8,9]])

In [17]:
a+b

array([[ 7,  9],
       [12, 14]])

In [19]:
np.sum((a,b))

42

In [21]:
np.sum(a+b,axis=0) # rows 

array([19, 23])

In [24]:
np.sum(a+b,axis=1)

array([16, 26])

In [25]:
a-b

array([[-5, -5],
       [-4, -4]])

In [26]:
np.sum(a-b)

-18

In [27]:
np.sum(a-b,axis=0)

array([-9, -9])

In [28]:
np.sum(a-b,axis=1)

array([-10,  -8])

In [29]:
a*b

array([[ 6, 14],
       [32, 45]])

In [30]:
np.dot(a,b)

array([[22, 25],
       [64, 73]])

In [31]:
a/b

array([[0.16666667, 0.28571429],
       [0.5       , 0.55555556]])

In [32]:
a%b

array([[1, 2],
       [4, 5]], dtype=int32)

In [33]:
# some trigonometry
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [-0.7568025 , -0.95892427]])

In [34]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.65364362,  0.28366219]])

In [36]:
np.tan((a,b))

array([[[ 1.55740772, -2.18503986],
        [ 1.15782128, -3.38051501]],

       [[-0.29100619,  0.87144798],
        [-6.79971146, -0.45231566]]])

In [39]:
1/np.tan(a)

array([[ 0.64209262, -0.45765755],
       [ 0.86369115, -0.29581292]])

In [42]:
np.std((a,b))

2.6339134382131846

In [43]:
np.median(a)

3.0

In [44]:
a

array([[1, 2],
       [4, 5]])

In [45]:
np.exp(a)

array([[  2.71828183,   7.3890561 ],
       [ 54.59815003, 148.4131591 ]])

In [46]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

In [48]:
# some linear algebra

# 10x +5y=30
# 20x +15y=45
a=np.array([[10,5],[20,15]])
b=np.array([30,45])

In [49]:
np.linalg.solve(a,b)

array([ 4.5, -3. ])

In [50]:
np.linalg.det(a)

49.99999999999999

In [55]:
np.vstack((a,b))

array([[10,  5],
       [20, 15],
       [30, 45]])

In [52]:
a

array([[10,  5],
       [20, 15]])

In [56]:
b

array([30, 45])

In [58]:
c=np.array([[1,2],[3,4]])

In [59]:
np.hstack((a,c))

array([[10,  5,  1,  2],
       [20, 15,  3,  4]])

**Pandas**
- python was majorly used for data munging and preparation.
- data analysis
- data maniulation
- data cleaning
- homogenous
- it provides a flexable way to merge,concatinate or reshape data

In [ ]:
**notations**
- Series
- DataFrame

In [64]:
import pandas as pd
a=pd.Series([1,2,3,6.8,"a"])
a

0      1
1      2
2      3
3    6.8
4      a
dtype: object

In [67]:
# slicing
a[3:]

3    6.8
4      a
dtype: object

In [70]:
b=pd.DataFrame([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
b

0  1  2   3
0  1  2  3   4
1  4  5  6   7
2  7  8  9  10

In [71]:
print(dir(pd),end="")

['Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NaT', 'Panel', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseDtype', 'SparseSeries', 'TimeGrouper', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_hashtable', '_lib', '_libs', '_np_version_under1p13', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_tslib', '_version', 'api', 'array', 'arrays', 'bdate_rang

In [72]:
a=[1,2,3,4]
b=[4,5,6,7]
c=[8,9,10,11]

In [73]:
pd.DataFrame({"a":a,"b":b,"c":c})

a  b   c
0  1  4   8
1  2  5   9
2  3  6  10
3  4  7  11

In [75]:
c=pd.read_csv("sample.csv")
c

name  rollno claname  m1  m2  m3  m4
0   n1     101     sdc  67  78  56  87
1   n2     102     sdc  78  67  87  98
2   n3     103     sdc  87  56  45  23

In [77]:
d=pd.read_csv("income.csv")
d

Index                 State    Y2002    Y2003    Y2004    Y2005    Y2006  \
0      A               Alabama  1296530  1317711  1118631  1492583  1107408   
1      A                Alaska  1170302  1960378  1818085  1447852  1861639   
2      A               Arizona  1742027  1968140  1377583  1782199  1102568   
3      A              Arkansas  1485531  1994927  1119299  1947979  1669191   
4      C            California  1685349  1675807  1889570  1480280  1735069   
5      C              Colorado  1343824  1878473  1886149  1236697  1871471   
6      C           Connecticut  1610512  1232844  1181949  1518933  1841266   
7      D              Delaware  1330403  1268673  1706751  1403759  1441351   
8      D  District of Columbia  1111437  1993741  1374643  1827949  1803852   
9      F               Florida  1964626  1468852  1419738  1362787  1339608   
10     G               Georgia  1929009  1541565  1810773  1779091  1326846   
11     H                Hawaii  1461570  1200280  1213993  1245931  1459383   
12     I                 Idaho  1353210  1438538  1739154  1541015  1122387   
13     I              Illinois  1508356  1527440  1493029  1261353  1540274   
14     I               Indiana  1776918  1734104  1269927  1204117  1848073   
15     I                  Iowa  1499269  1444576  1576367  1388924  1554813   
16     K                Kansas  1509054  1290700  1522230  1532094  1104256   
17     K              Kentucky  1813878  1448846  1800760  1250524  1137913   
18     L             Louisiana  1584734  1110625  1868456  1751920  1233709   
19     M                 Maine  1582720  1678622  1208496  1912040  1438549   
20     M              Maryland  1579713  1404700  1849798  1397738  1310270   
21     M         Massachusetts  1647582  1686259  1620601  1777250  1531641   
22     M              Michigan  1295635  1149931  1601027  1340716  1729449   
23     M             Minnesota  1729921  1675204  1903907  1561839  1985692   
24     M           Mississippi  1983285  1292558  1631325  1943311  1354579   
25     M              Missouri  1221316  1858368  1773451  1573967  1374863   
26     M               Montana  1877154  1540099  1332722  1273327  1625721   
27     N              Nebraska  1885081  1309769  1425527  1240465  1500594   
28     N                Nevada  1426117  1114500  1119707  1758830  1694526   
29     N         New Hampshire  1419776  1854370  1195119  1990062  1645430   
30     N            New Jersey  1605532  1141514  1613550  1181452  1541327   
31     N            New Mexico  1819239  1226057  1935991  1124400  1723493   
32     N              New York  1395149  1611371  1170675  1446810  1426941   
33     N        North Carolina  1616742  1292223  1482792  1532347  1158716   
34     N          North Dakota  1618807  1510193  1876940  1443172  1425030   
35     O                  Ohio  1802132  1648498  1441386  1670280  1534888   
36     O              Oklahoma  1173918  1334639  1663622  1798714  1312574   
37     O                Oregon  1794912  1726665  1805445  1133510  1502242   
38     P          Pennsylvania  1320191  1446723  1218591  1122030  1971479   
39     R          Rhode Island  1501744  1942942  1266657  1961923  1835983   
40     S        South Carolina  1631522  1803455  1425193  1458191  1538731   
41     S          South Dakota  1159037  1150689  1660148  1417141  1418586   
42     T             Tennessee  1811867  1485909  1974179  1157059  1786132   
43     T                 Texas  1520591  1310777  1957713  1907326  1873544   
44     U                  Utah  1771096  1195861  1979395  1241662  1437456   
45     V               Vermont  1146902  1832249  1492704  1579265  1332048   
46     V              Virginia  1134317  1163996  1891068  1853855  1708715   
47     W            Washington  1977749  1687136  1199490  1163092  1334864   
48     W         West Virginia  1677347  1380662  1176100  1888948  1922085   
49     W             Wisconsin  1788920  1518578  128

In [80]:
d.head(2)

Index    State    Y2002    Y2003    Y2004    Y2005    Y2006    Y2007  \
0     A  Alabama  1296530  1317711  1118631  1492583  1107408  1440134   
1     A   Alaska  1170302  1960378  1818085  1447852  1861639  1465841   

     Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014    Y2015  
0  1945229  1944173  1237582  1440756  1186741  1852841  1558906  1916661  
1  1551826  1436541  1629616  1230866  1512804  1985302  1580394  1979143

In [81]:
d.tail()

Index          State    Y2002    Y2003    Y2004    Y2005    Y2006    Y2007  \
46     V       Virginia  1134317  1163996  1891068  1853855  1708715  1197698   
47     W     Washington  1977749  1687136  1199490  1163092  1334864  1621989   
48     W  West Virginia  1677347  1380662  1176100  1888948  1922085  1740826   
49     W      Wisconsin  1788920  1518578  1289663  1436888  1251678  1721874   
50     W        Wyoming  1775190  1498098  1198212  1881688  1750527  1523124   

      Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014    Y2015  
46  1803330  1590043  1516758  1171686  1262342  1647032  1706707  1850394  
47  1545621  1555554  1179331  1150089  1775787  1273834  1387428  1377341  
48  1238174  1539322  1539603  1872519  1462137  1683127  1204344  1198791  
49  1980167  1901394  1648755  1940943  1729177  1510119  1701650  1846238  
50  1587602  1504455  1282142  1881814  1673668  1994022  1204029  1853858

In [82]:
d.tail(3)

Index          State    Y2002    Y2003    Y2004    Y2005    Y2006    Y2007  \
48     W  West Virginia  1677347  1380662  1176100  1888948  1922085  1740826   
49     W      Wisconsin  1788920  1518578  1289663  1436888  1251678  1721874   
50     W        Wyoming  1775190  1498098  1198212  1881688  1750527  1523124   

      Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014    Y2015  
48  1238174  1539322  1539603  1872519  1462137  1683127  1204344  1198791  
49  1980167  1901394  1648755  1940943  1729177  1510119  1701650  1846238  
50  1587602  1504455  1282142  1881814  1673668  1994022  1204029  1853858

In [83]:
d.shape

(51, 16)

In [86]:
d["Y2002"].describe()

count    5.100000e+01
mean     1.566034e+06
std      2.464425e+05
min      1.111437e+06
25%      1.374180e+06
50%      1.584734e+06
75%      1.776054e+06
max      1.983285e+06
Name: Y2002, dtype: float64

In [90]:
d.info

<bound method DataFrame.info of    Index                 State    Y2002    Y2003    Y2004    Y2005    Y2006  \
0      A               Alabama  1296530  1317711  1118631  1492583  1107408   
1      A                Alaska  1170302  1960378  1818085  1447852  1861639   
2      A               Arizona  1742027  1968140  1377583  1782199  1102568   
3      A              Arkansas  1485531  1994927  1119299  1947979  1669191   
4      C            California  1685349  1675807  1889570  1480280  1735069   
5      C              Colorado  1343824  1878473  1886149  1236697  1871471   
6      C           Connecticut  1610512  1232844  1181949  1518933  1841266   
7      D              Delaware  1330403  1268673  1706751  1403759  1441351   
8      D  District of Columbia  1111437  1993741  1374643  1827949  1803852   
9      F               Florida  1964626  1468852  1419738  1362787  1339608   
10     G               Georgia  1929009  1541565  1810773  1779091  1326846   
11     H            

In [91]:
d.values

array([['A', 'Alabama', 1296530, 1317711, 1118631, 1492583, 1107408,
        1440134, 1945229, 1944173, 1237582, 1440756, 1186741, 1852841,
        1558906, 1916661],
       ['A', 'Alaska', 1170302, 1960378, 1818085, 1447852, 1861639,
        1465841, 1551826, 1436541, 1629616, 1230866, 1512804, 1985302,
        1580394, 1979143],
       ['A', 'Arizona', 1742027, 1968140, 1377583, 1782199, 1102568,
        1109382, 1752886, 1554330, 1300521, 1130709, 1907284, 1363279,
        1525866, 1647724],
       ['A', 'Arkansas', 1485531, 1994927, 1119299, 1947979, 1669191,
        1801213, 1188104, 1628980, 1669295, 1928238, 1216675, 1591896,
        1360959, 1329341],
       ['C', 'California', 1685349, 1675807, 1889570, 1480280, 1735069,
        1812546, 1487315, 1663809, 1624509, 1639670, 1921845, 1156536,
        1388461, 1644607],
       ['C', 'Colorado', 1343824, 1878473, 1886149, 1236697, 1871471,
        1814218, 1875146, 1752387, 1913275, 1665877, 1491604, 1178355,
        1383978, 1330

In [92]:
d.head()

Index       State    Y2002    Y2003    Y2004    Y2005    Y2006    Y2007  \
0     A     Alabama  1296530  1317711  1118631  1492583  1107408  1440134   
1     A      Alaska  1170302  1960378  1818085  1447852  1861639  1465841   
2     A     Arizona  1742027  1968140  1377583  1782199  1102568  1109382   
3     A    Arkansas  1485531  1994927  1119299  1947979  1669191  1801213   
4     C  California  1685349  1675807  1889570  1480280  1735069  1812546   

     Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014    Y2015  
0  1945229  1944173  1237582  1440756  1186741  1852841  1558906  1916661  
1  1551826  1436541  1629616  1230866  1512804  1985302  1580394  1979143  
2  1752886  1554330  1300521  1130709  1907284  1363279  1525866  1647724  
3  1188104  1628980  1669295  1928238  1216675  1591896  1360959  1329341  
4  1487315  1663809  1624509  1639670  1921845  1156536  1388461  1644607

In [93]:
c

name  rollno claname  m1  m2  m3  m4
0   n1     101     sdc  67  78  56  87
1   n2     102     sdc  78  67  87  98
2   n3     103     sdc  87  56  45  23

In [96]:
c.set_index('name',inplace=True)

In [97]:
c

rollno claname  m1  m2  m3  m4
name                                
n1       101     sdc  67  78  56  87
n2       102     sdc  78  67  87  98
n3       103     sdc  87  56  45  23

In [99]:
c["rollno"]

name
n1    101
n2    102
n3    103
Name: rollno, dtype: int64

In [100]:
c["name"]

KeyError: 'name'

In [106]:
c.sort_values("m3",ascending=True)

rollno claname  m1  m2  m3  m4
name                                
n3       103     sdc  87  56  45  23
n1       101     sdc  67  78  56  87
n2       102     sdc  78  67  87  98

In [109]:
d.head()

Index       State    Y2002    Y2003    Y2004    Y2005    Y2006    Y2007  \
0     A     Alabama  1296530  1317711  1118631  1492583  1107408  1440134   
1     A      Alaska  1170302  1960378  1818085  1447852  1861639  1465841   
2     A     Arizona  1742027  1968140  1377583  1782199  1102568  1109382   
3     A    Arkansas  1485531  1994927  1119299  1947979  1669191  1801213   
4     C  California  1685349  1675807  1889570  1480280  1735069  1812546   

     Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014    Y2015  
0  1945229  1944173  1237582  1440756  1186741  1852841  1558906  1916661  
1  1551826  1436541  1629616  1230866  1512804  1985302  1580394  1979143  
2  1752886  1554330  1300521  1130709  1907284  1363279  1525866  1647724  
3  1188104  1628980  1669295  1928238  1216675  1591896  1360959  1329341  
4  1487315  1663809  1624509  1639670  1921845  1156536  1388461  1644607

In [110]:
d.set_index("Index",inplace=True)

In [112]:
d.head(10)

State    Y2002    Y2003    Y2004    Y2005    Y2006  \
Index                                                                      
A                   Alabama  1296530  1317711  1118631  1492583  1107408   
A                    Alaska  1170302  1960378  1818085  1447852  1861639   
A                   Arizona  1742027  1968140  1377583  1782199  1102568   
A                  Arkansas  1485531  1994927  1119299  1947979  1669191   
C                California  1685349  1675807  1889570  1480280  1735069   
C                  Colorado  1343824  1878473  1886149  1236697  1871471   
C               Connecticut  1610512  1232844  1181949  1518933  1841266   
D                  Delaware  1330403  1268673  1706751  1403759  1441351   
D      District of Columbia  1111437  1993741  1374643  1827949  1803852   
F                   Florida  1964626  1468852  1419738  1362787  1339608   

         Y2007    Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014  \
Index                                                                           
A      1440134  1945229  1944173  1237582  1440756  1186741  1852841  1558906   
A      1465841  1551826  1436541  1629616  1230866  1512804  1985302  1580394   
A      1109382  1752886  1554330  1300521  1130709  1907284  1363279  1525866   
A      1801213  1188104  1628980  1669295  1928238  1216675  1591896  1360959   
C      1812546  1487315  1663809  1624509  1639670  1921845  1156536  1388461   
C      1814218  1875146  1752387  1913275  1665877  1491604  1178355  1383978   
C      1976976  1764457  1972730  1968730  1945524  1228529  1582249  1503156   
D      1300836  1762096  1553585  1370984  1318669  1984027  1671279  1803169   
D      1595981  1193245  1739748  1707823  1353449  1979708  1912654  1782169   
F      1278550  1756185  1818438  1198403  1497051  1131928  1107448  1407784   

         Y2015  
Index           
A      1916661  
A      1979143  
A      1647724  
A      1329341  
C      1644607  
C      1330736  
C      1718072  
D      1627508  
D      1410183  
F      1170389

In [115]:
# iloc
d.iloc[5]

State    Colorado
Y2002     1343824
Y2003     1878473
Y2004     1886149
Y2005     1236697
Y2006     1871471
Y2007     1814218
Y2008     1875146
Y2009     1752387
Y2010     1913275
Y2011     1665877
Y2012     1491604
Y2013     1178355
Y2014     1383978
Y2015     1330736
Name: C, dtype: object

In [116]:
d.iloc[5:9]

State    Y2002    Y2003    Y2004    Y2005    Y2006  \
Index                                                                      
C                  Colorado  1343824  1878473  1886149  1236697  1871471   
C               Connecticut  1610512  1232844  1181949  1518933  1841266   
D                  Delaware  1330403  1268673  1706751  1403759  1441351   
D      District of Columbia  1111437  1993741  1374643  1827949  1803852   

         Y2007    Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014  \
Index                                                                           
C      1814218  1875146  1752387  1913275  1665877  1491604  1178355  1383978   
C      1976976  1764457  1972730  1968730  1945524  1228529  1582249  1503156   
D      1300836  1762096  1553585  1370984  1318669  1984027  1671279  1803169   
D      1595981  1193245  1739748  1707823  1353449  1979708  1912654  1782169   

         Y2015  
Index           
C      1330736  
C      1718072  
D      1627508  
D      1410183

In [121]:
d.loc["N"]

State    Y2002    Y2003    Y2004    Y2005    Y2006    Y2007  \
Index                                                                         
N            Nebraska  1885081  1309769  1425527  1240465  1500594  1278272   
N              Nevada  1426117  1114500  1119707  1758830  1694526  1765826   
N       New Hampshire  1419776  1854370  1195119  1990062  1645430  1286967   
N          New Jersey  1605532  1141514  1613550  1181452  1541327  1156804   
N          New Mexico  1819239  1226057  1935991  1124400  1723493  1475985   
N            New York  1395149  1611371  1170675  1446810  1426941  1463171   
N      North Carolina  1616742  1292223  1482792  1532347  1158716  1827420   
N        North Dakota  1618807  1510193  1876940  1443172  1425030  1868788   

         Y2008    Y2009    Y2010    Y2011    Y2012    Y2013    Y2014    Y2015  
Index                                                                          
N      1140598  1270585  1128711  1187207  1569665  1690920  1459243  1802211  
N      1903270  1231480  1526066  1143343  1980195  1283813  1225348  1903804  
N      1762936  1763211  1265642  1704297  1131298  1197576  1242623  1963313  
N      1568034  1357418  1443718  1390010  1202326  1100990  1850165  1183568  
N      1237704  1820856  1801430  1653384  1475715  1623388  1533494  1868612  
N      1732098  1426216  1604531  1683687  1500089  1718837  1619033  1367705  
N      1267737  1116168  1791535  1553750  1472258  1104893  1596452  1229085  
N      1720352  1671468  1534571  1271132  1430978  1529024  1563898  1604118

In [143]:
e=pd.DataFrame([["a",2],["b",3]],columns=["alphabets","numbers"])
f=pd.DataFrame([["c",4],["d",5]],columns=["alphabets","numbers"])

In [144]:
e

alphabets  numbers
0         a        2
1         b        3

In [145]:
f

alphabets  numbers
0         c        4
1         d        5

In [146]:
pd.concat([e,f])

alphabets  numbers
0         a        2
1         b        3
0         c        4
1         d        5

In [147]:
pd.concat([e,f],ignore_index=True)

alphabets  numbers
0         a        2
1         b        3
2         c        4
3         d        5

In [149]:
e1=pd.DataFrame([["a",2],["b",3]],columns=["alphabets","numbers"])
f1=pd.DataFrame([["c",4],["d",5]],columns=["alphabets2","numbers2"])

In [155]:
pd.concat([e1,f1],axis=1)

alphabets  numbers alphabets2  numbers2
0         a        2          c         4
1         b        3          d         5

In [157]:
d

State    Y2002    Y2003    Y2004    Y2005    Y2006  \
Index                                                                      
A                   Alabama  1296530  1317711  1118631  1492583  1107408   
A                    Alaska  1170302  1960378  1818085  1447852  1861639   
A                   Arizona  1742027  1968140  1377583  1782199  1102568   
A                  Arkansas  1485531  1994927  1119299  1947979  1669191   
C                California  1685349  1675807  1889570  1480280  1735069   
C                  Colorado  1343824  1878473  1886149  1236697  1871471   
C               Connecticut  1610512  1232844  1181949  1518933  1841266   
D                  Delaware  1330403  1268673  1706751  1403759  1441351   
D      District of Columbia  1111437  1993741  1374643  1827949  1803852   
F                   Florida  1964626  1468852  1419738  1362787  1339608   
G                   Georgia  1929009  1541565  1810773  1779091  1326846   
H                    Hawaii  1461570  1200280  1213993  1245931  1459383   
I                     Idaho  1353210  1438538  1739154  1541015  1122387   
I                  Illinois  1508356  1527440  1493029  1261353  1540274   
I                   Indiana  1776918  1734104  1269927  1204117  1848073   
I                      Iowa  1499269  1444576  1576367  1388924  1554813   
K                    Kansas  1509054  1290700  1522230  1532094  1104256   
K                  Kentucky  1813878  1448846  1800760  1250524  1137913   
L                 Louisiana  1584734  1110625  1868456  1751920  1233709   
M                     Maine  1582720  1678622  1208496  1912040  1438549   
M                  Maryland  1579713  1404700  1849798  1397738  1310270   
M             Massachusetts  1647582  1686259  1620601  1777250  1531641   
M                  Michigan  1295635  1149931  1601027  1340716  1729449   
M                 Minnesota  1729921  1675204  1903907  1561839  1985692   
M               Mississippi  1983285  1292558  1631325  1943311  1354579   
M                  Missouri  1221316  1858368  1773451  1573967  1374863   
M                   Montana  1877154  1540099  1332722  1273327  1625721   
N                  Nebraska  1885081  1309769  1425527  1240465  1500594   
N                    Nevada  1426117  1114500  1119707  1758830  1694526   
N             New Hampshire  1419776  1854370  1195119  1990062  1645430   
N                New Jersey  1605532  1141514  1613550  1181452  1541327   
N                New Mexico  1819239  1226057  1935991  1124400  1723493   
N                  New York  1395149  1611371  1170675  1446810  1426941   
N            North Carolina  1616742  1292223  1482792  1532347  1158716   
N              North Dakota  1618807  1510193  1876940  1443172  1425030   
O                      Ohio  1802132  1648498  1441386  1670280  1534888   
O                  Oklahoma  1173918  1334639  1663622  1798714  1312574   
O                    Oregon  1794912  1726665  1805445  1133510  1502242   
P              Pennsylvania  1320191  1446723  1218591  1122030  1971479   
R              Rhode Island  1501744  1942942  1266657  1961923  1835983   
S            South Carolina  1631522  1803455  1425193  1458191  1538731   
S              South Dakota  1159037  1150689  1660148  1417141  1418586   
T                 Tennessee  1811867  1485909  1974179  1157059  1786132   
T                     Texas  1520591  1310777  1957713  1907326  1873544   
U                      Utah  1771096  1195861  1979395  1241662  1437456   
V                   Vermont  1146902  1832249  1492704  1579265  1332048   
V                  Virginia  1134317  1163996  1891068  1853855  1708715   
W                Washington  1977749  1687136  1199490  1163092  1334864   
W             West Virginia  1677347  1380662  1176100  1888948  1922085   
W                 Wisconsin  1788920  1518578  1289663  1436888  1251678   
W                   Wyoming  1775190  1498098  1198212  1881688  17505

In [159]:
var=d["Y2002"]
var.count()
avg=sum(var)/var.count()
avg

1566034.1764705882